// One-off: turn NRC VAD v2.1's arousal unigrams into src/core/quality/arousalData.ts.
//   node scripts/buildArousal.mjs path/to/unigrams-arousal-NRC-VAD-Lexicon-v2.1.txt
// NRC VAD Lexicon, Saif M. Mohammad, National Research Council Canada.
import { readFileSync, writeFileSync } from 'node:fs'

const rows = readFileSync(process.argv[2], 'utf8').split(/\r?\n/).slice(1)
const lines = rows
  .map((row) => row.split('\t'))
  .filter(([word, score]) => /^[a-z']+$/.test(word ?? '') && score)
  .map(([word, score]) => `${word} ${Math.round(Number(score) * 100)}`)
writeFileSync(
  'src/core/quality/arousalData.ts',
  '// Generated by scripts/buildArousal.mjs from NRC VAD Lexicon v2.1 (Saif M. Mohammad, NRC Canada).\n' +
    '// "word score" per line, arousal from -100 to 100. Loaded on demand by arousal.ts.\n' +
    `export default ${JSON.stringify(lines.join('\n'))}\n`,
)
console.log(`${lines.length} words`)
