// One-off: turn NRC VAD v2.1's combined unigram file into src/core/quality/vadData.ts.
//   node scripts/buildVad.mjs [path]
// The path defaults to scripts/data/nrcVad, which is gitignored: only the generated file ships.
// Unigrams only. NRC-VAD-Lexicon-v2.1.txt adds multi-word terms ("absolutely not"); using them needs a
// phrase matcher in vad.ts first.
// NRC VAD Lexicon, Saif M. Mohammad, National Research Council Canada.
import { readFileSync, writeFileSync } from 'node:fs'

const path = process.argv[2] ?? 'scripts/data/nrcVad/unigrams-NRC-VAD-Lexicon-v2.1.txt'
const score = (s) => Math.round(Number(s) * 100)

const lines = readFileSync(path, 'utf8')
  .split(/\r?\n/)
  .slice(1)
  .map((row) => row.split('\t'))
  .filter(([word, v, a, d]) => /^[a-z']+$/.test(word ?? '') && v && a && d)
  .map(([word, v, a, d]) => `${word} ${score(v)} ${score(a)} ${score(d)}`)

writeFileSync(
  'src/core/quality/vadData.ts',
  '// Generated by scripts/buildVad.mjs from NRC VAD Lexicon v2.1 (Saif M. Mohammad, NRC Canada).\n' +
    '// "word valence arousal dominance" per line, each from -100 to 100. Loaded on demand by vad.ts.\n' +
    `export default ${JSON.stringify(lines.join('\n'))}\n`,
)
console.log(`${lines.length} words`)
